name: EC2 Image Builder

on:
  push:
    paths:
      - '**.pkr.hcl'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}

jobs:
  build:
    name: "Backing"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Packer
        run: cd scripts/bash && chmod +x install_packer.sh && ./install_packer.sh

      - run: packer --version

      - name: Build Image
        run: cd scripts/packer && packer init . && packer build -var 'aws_access_key=$AWS_ACCESS_KEY' -var 'aws_secret_key=$AWS_SECRET_KEY' .